version: "2"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www/html/
        networks:
            - default
volumes:
    persistent: